<?php

namespace AppBundle\Repository;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByHasgtag($hashtag){
        $qb=$this->getEntityManager()->createQueryBuilder();
        return $qb->select('tweet')
            ->from('AppBundle:Tweet', 'tweet')
            ->where($qb->expr()->like('tweet.hashtags', '?1'))
            ->setParameter(1, "%$hashtag%")
            ->getQuery()
            ->getResult();
    }

    public function findAllCategories()
    {
        $qb=$this->getEntityManager()->createQueryBuilder();
        $results = $qb->select('tweet.category')->distinct()
            ->from('AppBundle:Tweet', 'tweet')
            ->getQuery()
            ->getResult();
        $simplecat = [];
        foreach($results as $result){
            array_push($simplecat, $result['category']);
        }
        return $simplecat;

    }
}
